language: r
cache: packages

before_install:
  - cd Rlib

matrix:
  include:
  - r: devel
    os: linux
  - r: release
    os: linux
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: release
    os: osx
  - r: release
    os: windows
  allow_failures:
  - r: devel
  